development:
  adapter: postgresql
  encoding: utf8
  database: appforfour_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: appforfour_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: appforfour_production
  pool: 5
  username:
  password: